name: Build, bump tag version and release

on:
  push:
    branches:
      - master

jobs:
  bump:
    name: Bump tag version
    runs-on: ubuntu-latest
    outputs:
      newtag: ${{ steps.bump_version.outputs.new_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: cargo build --release --locked

      - name: Bump version and push tag/create release point
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
        id: bump_version

  release-linux:
    name: Build and Release Linux
    needs: bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: cargo build --release --locked
        
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/r42
          asset_name: r42-linux-amd64
          tag: ${{ needs.bump.outputs.newtag }}
          overwrite: true

  release-windows:
    name: Build and Release Windows
    needs: bump
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: cargo build --release --locked
        
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/r42.exe
          asset_name: r42-windows-amd64.exe
          tag: ${{ needs.bump.outputs.newtag }}
          overwrite: true